export const RECEIVE_PLACES_REQUEST = "RECEIVE_PLACES_REQUEST"
export const RECEIVE_PLACES_SUCCESS = "RECEIVE_PLACES_SUCCESS"
export const RECEIVE_PLACES_FAILURE = "RECEIVE_PLACES_FAILURE"
export const TOGGLE_PLACE_TYPE_SELECTION = "TOGGLE_PLACE_TYPE_SELECTION"
